### ISSUE TITLE
visualize autodock vina results

### ISSUE THREAD

**Issue by R-Stefano** [epam/miew#538]
Is it possible to visualize the ligand-protein interactions from a pdbqt files generated by vina? 

I can't seem to find any example for it in the docs. Also, when I simply load [this pdbqt file](https://raw.githubusercontent.com/sha256feng/Autodock-vina-example/master/out-10modes.pdbqt) it shows only some atoms

**Comment by paulsmirnov** [comment]
Hi @R-Stefano. Unfortunately, Miew doesn't support `.pdbqt` files. If you try to load a file with such an extension in [the demo](https://miew.app), it shows a message:

> Only the following filename extensions are supported: .ccp4, .cif, .cml, .dsn6, .ent, .gro, .json, .map, .ml2, .mmcif, .mmtf, .mol, .mol2, .mrc, .omap, .pdb, .sdf, .sy2, .xyz

It is not the latest version of the application but the behavior hasn't changed since then.

If you force it to load the file, it shows some atoms, but remember that the formats are physically different in some aspects. I've looked through the documentation, and here are my concerns:
- PDBQT uses positions 67-76 to encode partial charges. In PDB these are used for naming chain segments (73-76),
- PDBQT uses positions 78-79 to encode AutoDock atom types. In PDB they are used for the chemical element symbol (77-78) and charge (79-80).

Hence, the fields conflict and data corruption (may) happen. There are more differences in tags and their structure.

If you want to open the file, you need to convert it to PDB first. I see some advice to run it through [open babel](https://openbabel.org/) on the internet:
```
babel -ipdbqt 'file.pdbqt' -opdb 'file.pdb'
```

Another option is to keep ATOM records only and strip unwanted fields. In Linux/bash:
```
cat file.pdbqt | grep ATOM | cut -c-66 > file.pdb
```

**Comment by paulsmirnov** [comment]
Closing, as I hope I have answered the question.
